server:
  port: 8401
spring:
  application:
    name: sentinel
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.23.132:1111
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
      datasource:
        ds1:
         nacos:
           server-addr: 192.168.23.132:1111
           dataId: sentinel
           groupId: DEFAULT_GROUP
           data-type: json
           rule-type: flow
           namespace: public
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true


